
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
  namespace: kube-authentication
data:
  config.yaml: |
    issuer: https://10.197.37.202:30010
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    staticClients:
    - id: dex
      redirectURIs:
      - 'http://10.197.37.202:32000/callback'
      name: 'gangway'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    - id: harbor
      redirectURIs:
      - 'https://harbor-01.demo.local:30003/c/oidc/callback'
      name: 'harbor'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    - id: grafana
      redirectURIs:
      - 'http://10.197.37.202:31506/login/generic_oauth'
      name: 'grafana'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    connectors:
    - type: ldap
      name: OpenLDAP
      id: ldap
      config:
        host: 100.66.172.239
        # No TLS for this setup.
        insecureNoSSL: true
        # This would normally be a read-only user.
        bindDN: cn=admin,dc=example,dc=org
        bindPW: admin
        usernamePrompt: User Name 
        userSearch:
          baseDN: dc=example,dc=org
          filter: "(objectClass=posixaccount)"
          username: uid
          # "DN" (case sensitive) is a special attribute name. It indicates that
          # this value should be taken from the entity's DN not an attribute on
          # the entity.
          idAttr: DN
          emailAttr: mail
          nameAttr: cn 
        groupSearch:
          baseDN: ou=Groups,dc=example,dc=org
          # Optional filter to apply when searching the directory.
          filter: "(objectClass=posixGroup)"

          # Following two fields are used to match a user to a group. It adds an additional
          # requirement to the filter that an attribute in the group must match the user's
          # attribute value.
          userAttr: uid
          groupAttr: memberUid
          nameAttr: cn
      oauth2:
        skipApprovalScreen: true
      enablePasswordDB: true
