apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: kube-authentication
spec:
  type: NodePort
  ports:
  - name: dex
    port: 5556
    protocol: TCP
    targetPort: 5556
    nodePort: 30010
  selector:
    app: dex
