kind: Service
apiVersion: v1
metadata:
  name: gangway-svc
  namespace: kube-authentication
  labels:
    app: gangway
spec:
  type: NodePort
  ports:
    - name: "http"
      protocol: TCP
      nodePort: 32000
      port: 8080
      targetPort: "http"
  selector:
    app: gangway
