apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin-controller
  namespace: kube-authentication
  labels:
    app: phpldapadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
        - name: phpldapadmin
          image: osixia/phpldapadmin:0.8.0
          ports:
            - containerPort: 80
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: "ldap-service"
            - name: PHPLDAPADMIN_SERVER_ADMIN
              value: "webmaster@example.org"
            - name: PHPLDAPADMIN_SERVER_PATH
              value: "/phpldapadmin"
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
