apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpldapadmin
  name: phpldapadmin-service
  namespace: kube-authentication
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31000
  selector:
    app: phpldapadmin
